MakerBistro/config/routes.rb
MakerBistro::Application.routes.draw do
  root 'menu_items#index'

  resources :menu_items do
    resources :ingredients
  end

end

MakerBistro/app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :ingredient_menu_items
  has_many :menu_items, through: :ingredient_menu_items
end

MakerBistro/app/models/ingredient_menu_item.rb
class IngredientMenuItem < ActiveRecord::Base
  belongs_to :ingredient
  belongs_to :menu_item
end

MakerBistro/app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  has_many :ingredient_menu_items
  has_many :ingredients, through: :ingredient_menu_items
end

MakerBistro/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

MakerBistro/app/controllers/ingredient_menu_items_controller.rb
class IngredientMenuItemsController < ApplicationController
end

MakerBistro/app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def create
    @menu_item = MenuItem.find(params[:menu_item_id])
    @ingredient = @menu_item.ingredients.create(ingredient_params)
    if @ingredient.save(ingredient_params)
      redirect_to menu_items_path
    end
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end

end

MakerBistro/app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController

  def index
    @menu_items = MenuItem.all
    @ingredients = Ingredient.all
  end

  def show
    @menu_item = MenuItem.find(params[:id])
    @ingredient = Ingredient.new
  end

end

MakerBistro/app/helpers/application_helper.rb
module ApplicationHelper
end

MakerBistro/app/helpers/ingredient_menu_items_helper.rb
module IngredientMenuItemsHelper
end

MakerBistro/app/helpers/ingredients_helper.rb
module IngredientsHelper
end

MakerBistro/app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

MakerBistro/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MakerBistro</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

MakerBistro/app/views/layouts/application.html.haml
%html
  %head
    %title MakerBistro
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = yield

MakerBistro/app/views/menu_items/index.html.haml
%h2 MakerBistro Menu
- @menu_items.each do |item|
  = item.name
  =link_to 'Show', menu_item_path(item.id)
  %br
  = item.price
  %br
  %br

MakerBistro/app/views/menu_items/show.html.haml
%h2 Item & Ingredients
%h3
  = @menu_item.name
- @menu_item.ingredients.each do |ing|
  = ing.name
  %br

= form_for([@menu_item, @ingredient], url: menu_item_ingredients_path(@menu_item.id)) do |f|
  = f.label :name
  = f.text_field :name
  = f.submit